---
title: "Untitled"
author: "Veith Weilnhammer"
date: "2023-09-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Abstract: **We propose that between-mode fluctuations may generate unambiguous error signals that enable optimal inference and learning in volatile environments.**

Introduction: 

Following our deletion of the section 5.8, we have adapted the last sentence of the abstract and the last paragraph of the introduction: 
- **We propose that between-mode fluctuations may generate unambiguous error signals that enable optimal inference and learning in volatile environments.**
- **When less sensitive to external stimulus information, humans and mice did not behave more randomly, but showed stronger serial dependencies in their perceptual choices[@fischer_serial_2014; @Liberman2014; @Abrahamyan2016; @Cicchini2014; @Cicchini2017; @Fritsche2020; @Urai2017; @Akrami2018; @Braun2018; @Bergen2019; @Urai2019; @Hsu2020].** These serial dependencies may be understood as driven by internal predictions that reflect the auto-correlation of natural environments[@Dong1995] and bias perception toward preceding experiences[@Burr2014; @Braun2018; @Bergen2019]. Computational modeling indicated that ongoing changes in perceptual performance may be driven by systematic fluctuations between externally- and internally-oriented modes of sensory analysis. **We discuss that such *bimodal inference* may help to build stable internal representations of the sensory environment despite an ongoing stream of sensory information.**.

We have removed the double reporting of uncontrolled and controlled stats. The following changes have been made:
- Group-level autocorrelation curves in humans: **In line with previous work[@Dehaene1993], we found that the probability of stimulus-congruence was not independent across successive trials: At the group level, stimulus-congruent perceptual choices were significantly autocorrelated for up to `r min(which(Summary_acf[Summary_acf$Variable == "diff_acf_Stimulus",]$p == "> 0.05")) - 1` trials (Figure 2B), controlling for task difficulty and the sequence of presented stimuli (Supplemental Figure 2A-B). (...) In close analogy to stimulus-congruence, we found history-congruence to be significantly autocorrelated for up to `r min(which(Summary_acf[Summary_acf$Variable == "diff_acf_History",]$p == "> 0.05")) - 1` trials (Figure 2B), while controlling for task difficulty and the sequence of presented stimuli (Supplemental Figure 2A-B).**
- Group-level autocorrelation curves in mice: **At the group level, we found a significant autocorrelations in both stimulus-congruence (`r min(which(M_Summary_acf[M_Summary_acf$Variable == "diff_acf_Stimulus",]$p == "> 0.05")) - 1` consecutive trials) and history-congruence (`r min(which(M_Summary_acf[M_Summary_acf$Variable == "diff_acf_History",]$p == "> 0.05")) - 1` consecutive trials (Figure XB), while controlling for the respective autocorrelation of task difficulty and external stimulation (Supplemental Figure 2C-D).**
- Correlation between stimulus- and history-congruence in humans: **When perceptual choices were less biased toward external information, participants relied more strongly on internal information acquired from perceptual history (and vice versa, $\beta$ = $`r STAT.slider_History_Preferred_vs_Accuracy$coefficients[2,1]`$ ± $`r STAT.slider_History_Preferred_vs_Accuracy$coefficients[2,2]`$, T($`r STAT.slider_History_Preferred_vs_Accuracy$coefficients[2,3]`$) = $`r STAT.slider_History_Preferred_vs_Accuracy$coefficients[2,4]`$, p = $`r STAT.slider_History_Preferred_vs_Accuracy$coefficients[2,5]`$, **controlling for fluctuations in general response biases**; Supplemental Section X.X).**
- Correlation between stimulus- and history-congruence in mice: **Fluctuations in the strength of history-congruent biases had a significant effect on stimulus-congruence ($\beta_1$ = $`r M_STAT.slider_History_Preferred_vs_Accuracy$coefficients[2,1]`$ ± $`r M_STAT.slider_History_Preferred_vs_Accuracy$coefficients[2,2]`$, T($`r M_STAT.slider_History_Preferred_vs_Accuracy$coefficients[2,3]`$) = $`r M_STAT.slider_History_Preferred_vs_Accuracy$coefficients[2,4]`$, p = $`r M_STAT.slider_History_Preferred_vs_Accuracy$coefficients[2,5]`$) beyond the effect of ongoing changes in general response biases ($\beta_2$ = $`r M_STAT.slider_History_Preferred_vs_Accuracy$coefficients[3,1]`$ ± $`r M_STAT.slider_History_Preferred_vs_Accuracy$coefficients[3,2]`$, T($`r M_STAT.slider_History_Preferred_vs_Accuracy$coefficients[3,3]`$) = $`r M_STAT.slider_History_Preferred_vs_Accuracy$coefficients[3,4]`$, p = $`r M_STAT.slider_History_Preferred_vs_Accuracy$coefficients[3,5]`$).**

To further streamline our manuscript, we have moved more peripheral statistical results to the figure legends and the method section. The following changes have been made: 
- We have moved the statistics on exponential decay in the autocorrelation to the figure legends of Figure XB and XB.
- We have shortened the description of logistic regression models that predict the stimulus- and history-congruence at the index trial from the stimulus- and history-congruence at the preceding trials.
- The section on mouse behavior now matches the logic and presentation of results in the human section.

Introduction of TD analysis in mice:
- **The above results confirm that fluctuations between internally- and externally biased modes generalize to perceptual decision-making in mice. As in humans, we hypothesized that bimodal inference modulates the decision variable[@Kepecs2008] that determines not only perceptual choices, but also downstream aspects of mouse behavior[@Kepecs2008].**

Null hypothesis testing in mice:
**Eliminating the dynamic fluctuations in history-congruence as a predictor of fluctuations in stimulus-congruence resulted in an increase in AIC by \delta_{AIC} + `r -delta_AIC_correlation_mice` (see Supplemental Section X.X for an in-depth assessment of general response bias).**

**When fitting full and history-conditioned psychometric curves to the data from the IBL database, we observed that internal mode processing was associated with a history-dependent increase in bias and lapse as well as a history-independent increase in threshold (Supplemental Section X.X and Supplemental Figure SX). Over time, the frequency of history-congruent choices increased alongside stimulus-congruence and speed of response as mice were exposed to the experiment, arguing against the proposition that biases toward perceptual history reflected an unspecific response strategy in mice who were not sufficiently trained on the IBL task (Supplemental Section X.X)**. 

**In sum, these analyses confirmed that the observed fluctuations in sensitivity to external sensory information are driven by dynamic changes in impact of perceptual history, and cannot be reduced to general response bias and random choice behavior.**

**F. The bimodal inference model (M1) explains fluctuations between externally- and externally-biased modes (left panel) by two interacting factors: a normative accumulation of evidence according to parameters $H$ (middle panel), and anti-phase oscillations in the precision $\omega_{LLR}$ and $\omega_{\psi}$ (right panel).** 

**G. The control models (M2-M5) were constructed by successively removed the anti-phase oscillations and the integration of information across trials from the bimodal inference model. Please note that the normative-evidence-accumulation-model (M4) corresponds to the model proposed by Glaze et al.[@Glaze2015]. In the no-evidence-accumulation model (M5), perceptual decisions depend only on likelihood information (flat priors).** 


